name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features --release
      - name: Build
        run: cargo build --all-targets --all-features --release
      - name: Test
        run: cargo test --all-targets --all-features --release
      - name: Publish
        if: |
          github.repository == 'denoland/vnotify' &&
          startsWith(github.ref, 'refs/tags/')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish
